// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type AccountTokenEntity struct {
	BaseEntity
	AccountID     int       `gorm:"column:account_id;NOT NULL" json:"accountID"`                               // 关联账号表的ID
	Token      string    `gorm:"column:token;NOT NULL" json:"token"`                                 // token
	ExpireTime time.Time `gorm:"column:expire_time;default:CURRENT_TIMESTAMP;NOT NULL" json:"expireTime"` // 失效时间
}

func (m *AccountTokenEntity) TableName() string {
	return "account_token"
}

